# Generated by Django 5.0.6 on 2024-05-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curs_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('language_lvl', models.CharField(default='beginner', max_length=100)),
                ('learn_time', models.CharField(max_length=255, verbose_name='Learn time')),
                ('learn_price', models.CharField(max_length=255, verbose_name='Learn price')),
            ],
            options={
                'verbose_name': 'Curs',
                'verbose_name_plural': 'Cursy',
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
